name: DockerBuildOnRelease

on:
  release:
    types: 
      - created


jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

    - name: Get the Release/Tag Name
      id: tag
      run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

    - name: Print the Latest Release/Tag
      env:
          TAG_NAME: ${{ steps.tag.outputs.tag }}
      run: echo $TAG_NAME
